# configs/paths.yaml
directories:
  processed_data: "data/processed"
  output: "output"
  models: "models"

config_files:
  hyperparams: "configs/hyperparams.yaml"

models:
  embedding: "all-MiniLM-L6-v2"
  tiny_llama: "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
  
# please give this as an env variable. if you do, leave the "" blank. 
api_keys:
  openai: ""
